In [1]:
import numpy as np
data = np.array([[5.1, 1.4, 0],
                 [4.9, 1.4, 0],
                 [4.7, 1.3, 0],
                 [4.6, 1.5, 0],
                 [5.0, 1.4, 0],
                 [7.0, 4.7, 1],
                 [6.4, 4.5, 1],
                 [6.9, 4.9, 1],
                 [5.5, 4.0, 1],
                 [6.5, 4.6, 1]])
X = data[:,[0,1]]
y = data[:,2]

w_ = np.zeros(X.shape[1])
b_ = np.float64(0.)
losses_ = []
n_iter = 2
eta = 0.01

for _ in range(n_iter):
    # В случае Adaline мы можем определить функцию потерь L как среднеквадратичную ошибку
    # между функций активации(в ALN она аналогична фактическому входу Z = Xw + b) и истинной меткой класса:
    # L(w,b) = (сумма(уi-Zi)**2)/n
    # данная функция является параболой => один минимум => вычислив градиент этой функции мы сможем найти его
    # расчитав частные произвадные по w и b:
    # частная производная по w = -2/n*сумма((yi-Zi)*Xi)
    # частная производная по b = -2/n*сумма(yi-Zi)
    # Таким образом если смещать w и b в сторону противоположной градиенту функции потерь мы сможем быстрее найти
    # нужные значения:
    # дельта(w) = -скорость обучения * частная производная по w = 2*скорость обучения * mean((yi-Zi)*Xi)
    # дельта(b) = -скорость обучения * частная производная по b = 2*скорость обучения * mean(yi-Zi)

    errors = (y - np.dot(X,w_) + b_) # errors это массив содержащий разницы yi-Zi для каждого случая

    # сумму(yi-Zi)*Xi) можно представить как перемножение матрицы признаков X и вектора errors,
    # остаётся только разделить на n чтобы найти среднее
    w_ += eta * 2.0 * X.T.dot(errors) / X.shape[0]
    b_ += eta * 2.0 * errors.mean()
    loss = (errors**2).mean()
    print("весы",w_,"смещение",b_,"ошибки", errors, "ско",loss)
    print(X.T.dot(errors))

весы [0.0646 0.0454] смещение 0.01 ошибки [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.] ско 0.5
[32.3 22.7]
весы [0.07143754 0.05766417] смещение 0.010190520000000002 ошибки [-0.38302 -0.3701  -0.35264 -0.35526 -0.37656  0.34442  0.39226  0.3418
  0.4731   0.38126] ско 0.14345434828
[3.418768 6.132086]


In [2]:
display(X)
display(w_)
np.dot(X,w_)

array([[5.1, 1.4],
       [4.9, 1.4],
       [4.7, 1.3],
       [4.6, 1.5],
       [5. , 1.4],
       [7. , 4.7],
       [6.4, 4.5],
       [6.9, 4.9],
       [5.5, 4. ],
       [6.5, 4.6]])

array([0.07143754, 0.05766417])

array([0.44506127, 0.43077377, 0.41071984, 0.41510892, 0.43791752,
       0.77108436, 0.716689  , 0.77547344, 0.62356314, 0.72959918])